# Do not edit this file. Instead, make a copy of it and name it local_settings.R
# It will override any objects by the same name that are in this file.

deletebuttoncode <- "<button class='btn btn-danger btn-sm'><span class='glyphicon glyphicon-minus'></span></button>";
addbuttoncode <- "<span class='glyphicon glyphicon-plus'></span> Add Entry";
logdir <- file.path('.','logs');
apptitle <- "Care Manager Data Entry (temporary)";
userselfid_label <- "Your email address: ";
event_types <- c("","ED Visit", "IP Admit", "IP Discharge");
contracts <- c("","ACO-UT", "ACO-Community", "UTMA-Humana", "UTMA-WellMed");
outputfile <- 'caremanager_events.tsv';
email_validation_msg <- "Please enter your work email address to continue.";

c()